### ISSUE TITLE
Manual build instructions with DKMS cause a name error

### ISSUE THREAD

**Issue by Pipeline79** [emilyst/hid-nx-dkms#2]
Hi, I just followed the build instructions on ubuntu with dkms.
When I do the stage of adding the dkms module like so:
 `$ sudo dkms add .`
In the cloned directory.  
I get a link called '-dkms-v1.12' in /usr/src.  And the DKMS tree gets -dkms-v1.12 added as well.
Which is difficult to get rid of as well as not building - because the build command wants '/usr/src/hid-nx-1.12'.
Is it something I've done?  Or could there be an error in the repo somewhere?
Thanks.

**Comment by emilyst** [comment]
Sorry this happened to you. This is likely something I've done wrong on my part. I'll double-check it soon.

**Comment by emilyst** [comment]
I've confirmed this problem on my setup. The problem is due to the `dkms.conf` file (which is really just a shell file) referencing a variable before it was defined.

FYI: You can remove the spurious dkms tree with `sudo dkms remove -m '-dkms' -v 'v1.12'`. Use `dkms status` to verify this worked.

I'll push a new release with the fix momentarily.

**Comment by emilyst** [comment]
See release v1.13 for the fixed version. Hope this helps! Reopen if it doesn't. Open a new issue if there's some other problem. Thanks!

**Comment by Pipeline79** [comment]
Hi Emily,

Thanks very much for helping so quickly!  I'm sure what you've done will
have fixed it for me.
I spent ages trying to get a SNES online controller to connect last night -
I could get it to connect with bluetooth after much disconnecting and
reconnecting, but not usb.
In retroarch, with usb, the controller would appear as a device at times -
if I used udev as the input driver - but the buttons were unresponsive.
I could get it to work if I used bluetooth and stopped the joycond service
- but the whole thing seemed so random I'm not really sure what was going
on.
I was building the module from inside this arch package before:
https://aur.archlinux.org/hid-nintendo-nso-dkms.git
although I'm on Ubuntu. (I seemed to need it because my Ubuntu has a 5.15
series kernel)
Hopefully this module will give more reliable results, if that is the
problem.

Best regards,
Kevin.

**Comment by emilyst** [comment]
> Hopefully this module will give more reliable results, if that is the problem.

If it does, feel free to update.

**Comment by Pipeline79** [comment]
Yes - haven’t had any problems using the controller and pairing it since I
installed this module.

Thanks!

**Comment by emilyst** [comment]
I reread the note from earlier, and I believe what's happening is that the kernel module probably works fine in either case, but since mine uses slightly different names and inputs than the `hid-nintendo-nso` version, RetroArch cannot automatically configure it.

When RetroArch fails to configure a controller automatically, it seems to connect but doesn't do anything with the inputs. It appears as if the controller does not work. It is unfortunately inevitable that you will have to manually configure SNES inputs with `hid-nx` yourself in RetroArch.

You can rule out a kernel module issue by using `evtest` or `jstest` on the command line against the device and see its inputs there.
